spring:
  datasource:
    url: jdbc:postgresql://${PGPROXY}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

api:
  security:
    token:
      secret: ${TOKEN_SECRET}
